# Generated by Django 3.1.7 on 2021-07-14 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mall', '0002_auto_20210714_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_orderd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
