# Generated by Django 3.1.7 on 2021-07-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20210714_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_orderd',
        ),
    ]
